/**
 * Environment variable compatibility layer.
 *
 * Maps MYCLAUDE_* environment variables to CLAUDE_CODE_* equivalents,
 * so users can use either naming convention. CLAUDE_CODE_* takes priority
 * if both are set.
 *
 * Must be imported and called BEFORE any module that reads these env vars.
 */

// Map of MYCLAUDE_* -> CLAUDE_CODE_* aliases
const ENV_ALIASES: Record<string, string> = {
  // Model & API
  MYCLAUDE_MODEL: 'CLAUDE_CODE_MODEL',
  MYCLAUDE_BASE_URL: 'ANTHROPIC_BASE_URL',
  MYCLAUDE_API_KEY: 'ANTHROPIC_API_KEY',
  MYCLAUDE_AUTH_TOKEN: 'ANTHROPIC_AUTH_TOKEN',
  MYCLAUDE_MAX_OUTPUT_TOKENS: 'CLAUDE_CODE_MAX_OUTPUT_TOKENS',
  MYCLAUDE_EFFORT_LEVEL: 'CLAUDE_CODE_EFFORT_LEVEL',

  // Mode toggles
  MYCLAUDE_SIMPLE: 'CLAUDE_CODE_SIMPLE',
  MYCLAUDE_BRIEF: 'CLAUDE_CODE_BRIEF',
  MYCLAUDE_PROACTIVE: 'CLAUDE_CODE_PROACTIVE',
  MYCLAUDE_REMOTE: 'CLAUDE_CODE_REMOTE',
  MYCLAUDE_COORDINATOR_MODE: 'CLAUDE_CODE_COORDINATOR_MODE',

  // Feature flags
  MYCLAUDE_DISABLE_THINKING: 'CLAUDE_CODE_DISABLE_THINKING',
  MYCLAUDE_DISABLE_AUTO_MEMORY: 'CLAUDE_CODE_DISABLE_AUTO_MEMORY',
  MYCLAUDE_DISABLE_BACKGROUND_TASKS: 'CLAUDE_CODE_DISABLE_BACKGROUND_TASKS',
  MYCLAUDE_DISABLE_FEEDBACK_SURVEY: 'CLAUDE_CODE_DISABLE_FEEDBACK_SURVEY',
  MYCLAUDE_DISABLE_VIRTUAL_SCROLL: 'CLAUDE_CODE_DISABLE_VIRTUAL_SCROLL',
  MYCLAUDE_DISABLE_FILE_CHECKPOINTING: 'CLAUDE_CODE_DISABLE_FILE_CHECKPOINTING',

  // Cloud providers
  MYCLAUDE_USE_BEDROCK: 'CLAUDE_CODE_USE_BEDROCK',
  MYCLAUDE_USE_VERTEX: 'CLAUDE_CODE_USE_VERTEX',
  MYCLAUDE_USE_FOUNDRY: 'CLAUDE_CODE_USE_FOUNDRY',

  // UI / display
  MYCLAUDE_SYNTAX_HIGHLIGHT: 'CLAUDE_CODE_SYNTAX_HIGHLIGHT',
  MYCLAUDE_FORCE_FULL_LOGO: 'CLAUDE_CODE_FORCE_FULL_LOGO',
  MYCLAUDE_STREAMLINED_OUTPUT: 'CLAUDE_CODE_STREAMLINED_OUTPUT',
  MYCLAUDE_SCROLL_SPEED: 'CLAUDE_CODE_SCROLL_SPEED',
  MYCLAUDE_TMUX_SESSION: 'CLAUDE_CODE_TMUX_SESSION',
  MYCLAUDE_TMUX_PREFIX: 'CLAUDE_CODE_TMUX_PREFIX',
  MYCLAUDE_TMUX_PREFIX_CONFLICTS: 'CLAUDE_CODE_TMUX_PREFIX_CONFLICTS',

  // Session & system
  MYCLAUDE_IDLE_THRESHOLD_MINUTES: 'CLAUDE_CODE_IDLE_THRESHOLD_MINUTES',
  MYCLAUDE_SESSION_ID: 'CLAUDE_CODE_SESSION_ID',
  MYCLAUDE_ENTRYPOINT: 'CLAUDE_CODE_ENTRYPOINT',
  MYCLAUDE_GIT_BASH_PATH: 'CLAUDE_CODE_GIT_BASH_PATH',
  MYCLAUDE_DISABLE_PROMPT_SUGGESTION: 'CLAUDE_CODE_DISABLE_PROMPT_SUGGESTION',
  MYCLAUDE_ENABLE_PROMPT_SUGGESTION: 'CLAUDE_CODE_ENABLE_PROMPT_SUGGESTION',
  MYCLAUDE_OAUTH_TOKEN: 'CLAUDE_CODE_OAUTH_TOKEN',
  MYCLAUDE_OAUTH_CLIENT_ID: 'CLAUDE_CODE_OAUTH_CLIENT_ID',
  MYCLAUDE_CUSTOM_OAUTH_URL: 'CLAUDE_CODE_CUSTOM_OAUTH_URL',
  MYCLAUDE_NEW_INIT: 'CLAUDE_CODE_NEW_INIT',
  MYCLAUDE_EXIT_AFTER_FIRST_RENDER: 'CLAUDE_CODE_EXIT_AFTER_FIRST_RENDER',
  MYCLAUDE_SYNC_PLUGIN_INSTALL: 'CLAUDE_CODE_SYNC_PLUGIN_INSTALL',
  MYCLAUDE_DATADOG_FLUSH_INTERVAL_MS: 'CLAUDE_CODE_DATADOG_FLUSH_INTERVAL_MS',
  MYCLAUDE_API_KEY_HELPER_TTL_MS: 'CLAUDE_CODE_API_KEY_HELPER_TTL_MS',
  MYCLAUDE_API_KEY_FILE_DESCRIPTOR: 'CLAUDE_CODE_API_KEY_FILE_DESCRIPTOR',
  MYCLAUDE_OAUTH_TOKEN_FILE_DESCRIPTOR: 'CLAUDE_CODE_OAUTH_TOKEN_FILE_DESCRIPTOR',
  MYCLAUDE_OAUTH_REFRESH_TOKEN: 'CLAUDE_CODE_OAUTH_REFRESH_TOKEN',
  MYCLAUDE_OAUTH_SCOPES: 'CLAUDE_CODE_OAUTH_SCOPES',
  MYCLAUDE_OVERRIDE_DATE: 'CLAUDE_CODE_OVERRIDE_DATE',
  MYCLAUDE_ABLATION_BASELINE: 'CLAUDE_CODE_ABLATION_BASELINE',
  MYCLAUDE_OTEL_HEADERS_HELPER_DEBOUNCE_MS: 'CLAUDE_CODE_OTEL_HEADERS_HELPER_DEBOUNCE_MS',
}

/**
 * Apply MYCLAUDE_* -> CLAUDE_CODE_* environment variable aliases.
 *
 * For each alias pair, if the MYCLAUDE_* variable is set and the corresponding
 * CLAUDE_CODE_* variable is NOT set, copies the value across.
 *
 * Safe to call multiple times (idempotent).
 */
export function applyEnvAliases(): void {
  for (const [myclaudeKey, claudeCodeKey] of Object.entries(ENV_ALIASES)) {
    const myclaudeValue = process.env[myclaudeKey]
    if (myclaudeValue !== undefined && process.env[claudeCodeKey] === undefined) {
      process.env[claudeCodeKey] = myclaudeValue
    }
  }
}
